"""Correlation IDs for tracing a triage operation across logs/metrics/spans.

A ``correlation_id`` is a short opaque string generated when a triage
operation begins and carried through every event, metric label, and
trace span the operation emits. Consumers correlate the triage's log
events, the metrics it contributed to, and the trace span tree by
filtering on this ID.

The ID is generated by the framework (not caller-supplied) so a
deployment that doesn't bother to thread their own request ID still
gets a stable per-operation identifier. The ID is included in the
``TriageRecord`` (in the optional ``correlation_id`` field) so an
auditor can trace a stored record back to the operational log line
that produced it.

Generation: ``uuid.uuid4().hex[:16]`` (16-char lowercase hex slice of
a random UUID). Short enough to read in log lines, long enough that
collisions are astronomically unlikely (2**64 namespace; birthday
collision at ~4 billion IDs).

Format is intentionally opaque. Consumers should not parse it; treat
it as a token to filter on. The framework does not embed a timestamp,
counter, or hostname in the ID. Deployments wanting structured
identifiers can supply their own via the ``correlation_id`` parameter
on the future TriageAgent API extension; for 0.7.0, the framework
always generates its own.

The correlation ID does not appear in input submissions or schemas
beyond the output contract's optional ``correlation_id`` field. It is
not a security-sensitive identifier (does not contain PII or
operational secrets), so logging it freely is appropriate.
"""
from __future__ import annotations

import uuid


__all__ = ["new_correlation_id"]


def new_correlation_id() -> str:
    """Generate a fresh correlation ID for a single triage operation.

    Returns a 16-character lowercase hexadecimal string. The space is
    2**64; collisions across a single deployment's lifetime are
    astronomically unlikely.

    Stable per call; callers store the result and propagate it through
    the operation's events, metrics, and spans.
    """
    return uuid.uuid4().hex[:16]
